version: "3.9"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
        - ./web-code/:/var/www/html/
    networks:
      - php_nginx

  php:
    build: ./php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./web-code/:/var/www/html/
    networks:
      - php_nginx

  mysql:    
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes: 
      - ./mysql-data:/var/lib/mysql
    environment:  
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp
    networks:
      - php_nginx

networks:
    php_nginx:
  